from dna_from_pdb import *

class Pdb:
    def __init__(self, filename):
        self.atoms = atoms_from_pdb(filename)

    def write(self, atoms, out = open('atoms.pdb', 'w')):
        """Write selected atoms to pdb"""
        out.write('REMARK      generated by pdb.py\n')
        for atom in atoms:
            vals = (['ATOM', atom['atom_num'], atom['atom_name'],
                atom['res_name'], atom['res_num'],
                atom['x'], atom['y'], atom['z'],
                '1.00', '0.00', '\n'])
            line = '    '.join(str(v) for v in vals)
            out.write(line)

    def select(self, res = [], atom_name = []):
        """Select atoms by residue and element"""
        selection = (
            [atom for atom in self.atoms if atom['res_name'] in res
                and atom['atom_name'] in atom_name])
        return selection

b = Pdb('./pdb/ideal_bdna.pdb')

b.p = b.select(res = ['G'], atom_name = ['P'])
b.write(b.atoms)
